### ISSUE TITLE
Links clicked in Slack open in Safari only (Mac)

### ISSUE THREAD

**Issue by SeanWhipple** [mykeels/slack-theme-cli#20]
Not sure if this is known (or intended) or not...

But when I activate a new theme and click on a link in Slack it opens in Safari.  Chrome is set as my default browser and I have confirmed that other apps still respect this

**Comment by mykeels** [comment]
Interesting ... This only happens when you activate a theme?

**Comment by SeanWhipple** [comment]
Appears so... at least the first time.  Restarting Slack seems to get rid of the issue

**Comment by mykeels** [comment]
Sorry, I'm a little confused. It's been fixed since you restarted? If so, could you try switching themes again, to see if you can reproduce? 

I can't think of a reason a CSS theme would cause that behaviour.

**Comment by SeanWhipple** [comment]
Triggering a new theme was not able to reproduce... Weird.  I'll close for now as a non issue until I'm able to predictable repro the issue.  Not sure what happened here
