### ISSUE TITLE
Not working in MacOS Slack 3.3.8

### ISSUE THREAD

**Issue by zkrige** [mykeels/slack-theme-cli#21]
No longer working in MacOS slack v3.8.8

**Comment by mykeels** [comment]
Hi, what are you experiencing? @zkrige

**Comment by zkrige** [comment]
The command runs but slack theme stays white. It was working in previous versions of slack.

**Comment by mykeels** [comment]
Okay, I'm currently updating my slack.

In the meantime, could you uninstall with `slack-theme uninstall` and install again with the installation script in the README?

**Comment by zkrige** [comment]
Thank you. I tried that but it didn't seem to have any effect. Its still glaringly white

**Comment by mykeels** [comment]
Also, do you mean version 3.3.8? That's what I just got from updating Slack.

**Comment by zkrige** [comment]
my apologies - yes 3.3.8, not 3.8.8

**Comment by blanked** [comment]
I have some issues too on 3.3.8 on MacOS. Most of panels are ok except for the All Threads, where the background remains white no matter which profile is picked.

**Comment by mykeels** [comment]
This is currently being tracked upstream in https://github.com/laCour/slack-night-mode/issues/218

However, it's been fixed in this project. Run

```
slack-theme uninstall
```

Then run the appropriate installation script from the [README.md](https://github.com/mykeels/slack-theme-cli/blob/master/README.md)

**Comment by zkrige** [comment]
running the install script gives me the following error:
`slack-theme: line 342: /Applications/Slack.app/Contents/Resources/app.asar.unpacked/src/static/ssb-interop.js: Permission denied`

**Comment by mykeels** [comment]
```chmod 555  /Applications/Slack.app/Contents/Resources/app.asar.unpacked/src/static/ssb-interop.js```

should fix it @zkrige

**Comment by blanked** [comment]
oh yup i've reinstalled and its been fixed. thanks @mykeels !

**Comment by zkrige** [comment]
hmmm - still getting a permissions error

```sudo chmod 555 /Applications/Slack.app/Contents/Resources/app.asar.unpacked/src/static/ssb-interop.js
$ slack-theme arc-dark
sh: /Users/zayinkrige/.bash_profile
/Users/zayinkrige/bin/slack-theme/slack-theme: line 345: /Applications/Slack.app/Contents/Resources/app.asar.unpacked/src/static/ssb-interop.js: Permission denied```

**Comment by wbancer** [comment]
I made whole slack applicaton owned by my user not by root:
chown -R <myuser> /Applications/Slack.app
That solved any permission issues I had.

**Comment by mykeels** [comment]
Oh, cool @wbancer!

Does that help? @zkrige

**Comment by zkrige** [comment]
It helps until the next update which changes permissions again

**Comment by mykeels** [comment]
Looks like that's no longer directly affected by this app. I'll close the ticket.

Perhaps, you should reinstall Slack with the appropriate permissions.

**Comment by zkrige** [comment]
Slack was installed directly from App Store.

**Comment by mykeels** [comment]
Try using https://slack.com/intl/en-ng/downloads/windows

**Comment by zkrige** [comment]
I'm on a Mac :)
