### ISSUE TITLE
Left-hand channel list doesn't respect CSS change (3.3.8 - macOS Mojave)

### ISSUE THREAD

**Issue by the-dino-enthusiast** [mykeels/slack-theme-cli#22]
![image](https://user-images.githubusercontent.com/24962976/54303411-288d7380-4580-11e9-9e9a-f7326626229b.png)

No matter what theme I pick, I still get this grayed out left hand channel list which makes seeing room name difficult.

**Comment by mykeels** [comment]
Hi @the-dino-enthusiast

Slack's sidebar is styled differently. It's controlled by slack messages you can interact with to activate.

Here's one I use

```
#010203 ,#4a668f ,#152f47 ,#fbc02d ,#373a3d ,#e3dce3 ,#94E864 ,#78AF8F
```

Paste it in your Slack, then activate.

See more https://zapier.com/blog/customize-slack-sidebar/

**Comment by the-dino-enthusiast** [comment]
@mykeels - lol, thanks! I'm a n00b, sorry. 😛
