### ISSUE TITLE
slack-linux support

### ISSUE THREAD

**Issue by krull** [mykeels/slack-theme-cli#4]
Hey,

Cool script. Although I noticed that it is mostly Mac Centric.

**Comment by mykeels** [comment]
Hey @krull ... I'm working on a bunch of Powershell scripts that'd make it available for Windows. Would you like to help?

**Comment by krull** [comment]
@mykeels my apologies if the issue reported wasn't clear: As I noticed you were using this with `bash` in mind, I was thinking more generic-linux support to support [`slack-linux`](https://slack.com/downloads/linux).

**Comment by mykeels** [comment]
Now available for Linux Users! 🎉

**Comment by krull** [comment]
Thanks for working on this issue! Will try it and let you know!

Cheers.

@krull
