### ISSUE TITLE
macos mojave Permission Denied

### ISSUE THREAD

**Issue by giffysquid** [mykeels/slack-theme-cli#5]
Sorry for the dumb question, but I get a permission denied message when I run commands, like
`slack-theme day` or `slack-theme night`

This is the message I receive:

`~$ /Applications/Slack.app/Contents/Resources/app.asar.unpacked/src/static/ssb-interop.js: Permission denied`

Any tips for correcting this? Thanks for creating this tool. It looks awesome

**Comment by mykeels** [comment]
Try `sudo slack-theme night` ... for a short-term solution.

For a long-term solution, run `chmod 755 "/Applications/Slack.app/Contents/Resources/app.asar.unpacked/src/static/ssb-interop.js"` in terminal, which should allow your user to edit that file.

**Comment by giffysquid** [comment]
That worked beautifully. Thanks for the help!
